# SPDX-FileCopyrightText: 2023 Jose D. Montoya
#
# SPDX-License-Identifier: MIT

name: PyPI Release Actions

on:
  release:
    types: [published]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
    - name: Run PyPI Release CI workflow
      uses: jposada202020/workflows-circuitpython-libs/release-pypi@main
      with:
        pypi-username: ${{ secrets.pypi_username }}
        pypi-password: ${{ secrets.pypi_password }}
